# Generated by Django 2.1.5 on 2019-03-24 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('type', models.CharField(blank=True, max_length=3)),
                ('isPublic', models.BooleanField(default=False)),
                ('relatedPortafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kata.Portafolio')),
            ],
        ),
    ]
